FROM debian:bookworm

RUN apt-get update && apt-get install -y mariadb-server

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY tools/init_.sh /

RUN chmod +x /entrypoint.sh && \
    mkdir -p /run/mysqld && \
    chown -R mysql:mysql /run/mysqld

CMD ["/entrypoint.sh"]
