FROM debian:bookworm

RUN apt-get update && apt-get install -y php-fpm php-mysql curl

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

RUN mkdir -p /run/php /var/www/html

RUN sed -i 's|listen = /run/php/php8.2-fpm.sock|listen = 9000|g' /etc/php/8.2/fpm/pool.d/www.conf

COPY conf/setup.sh /setup.sh
RUN chmod +x /setup.sh

WORKDIR /var/www/html

CMD ["/setup.sh"]
